-- Create profiles table if it doesn't exist (assuming it's already created by Supabase Auth)
create table if not exists public.profiles (
    id uuid references auth.users on delete cascade not null primary key,
    email text unique not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create chats table
create table if not exists public.chats (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create chat_users junction table
create table if not exists public.chats_users (
    chat_id bigint references public.chats on delete cascade not null,
    user_id uuid references public.profiles on delete cascade not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    primary key (chat_id, user_id)
);

-- Create messages table
create table if not exists public.messages (
    id bigint generated by default as identity primary key,
    chat_id bigint references public.chats on delete cascade not null,
    author_id uuid references public.profiles on delete cascade not null,
    content text not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.profiles enable row level security;
alter table public.chats enable row level security;
alter table public.chats_users enable row level security;
alter table public.messages enable row level security;

-- Create policies for profiles
create policy "Users can view their own profile"
    on public.profiles for select
    using (auth.uid() = id);

create policy "Users can update their own profile"
    on public.profiles for update
    using (auth.uid() = id);

-- Create policies for chats
create policy "Users can view their chats"
    on public.chats for select
    using (
        exists (
            select 1 from public.chats_users
            where chat_id = chats.id
            and user_id = auth.uid()
        )
    );

create policy "Users can create chats"
    on public.chats for insert
    with check (true);

-- Create policies for chat_users
create policy "Users can view chat members"
    on public.chats_users for select
    using (
        exists (
            select 1 from public.chats_users
            where chat_id = chats_users.chat_id
            and user_id = auth.uid()
        )
    );

create policy "Users can add members to their chats"
    on public.chats_users for insert
    with check (
        exists (
            select 1 from public.chats_users
            where chat_id = chats_users.chat_id
            and user_id = auth.uid()
        )
    );

-- Create policies for messages
create policy "Users can view messages in their chats"
    on public.messages for select
    using (
        exists (
            select 1 from public.chats_users
            where chat_id = messages.chat_id
            and user_id = auth.uid()
        )
    );

create policy "Users can send messages to their chats"
    on public.messages for insert
    with check (
        exists (
            select 1 from public.chats_users
            where chat_id = messages.chat_id
            and user_id = auth.uid()
        )
    );

-- Enable real-time for the tables
alter publication supabase_realtime add table public.messages;
alter publication supabase_realtime add table public.chats;
alter publication supabase_realtime add table public.chats_users;

-- Create indexes for better performance
create index if not exists messages_chat_id_idx on public.messages(chat_id);
create index if not exists messages_author_id_idx on public.messages(author_id);
create index if not exists chats_users_chat_id_idx on public.chats_users(chat_id);
create index if not exists chats_users_user_id_idx on public.chats_users(user_id);

-- Create function to handle updated_at timestamps
create or replace function public.handle_updated_at()
returns trigger as $$
begin
    new.updated_at = timezone('utc'::text, now());
    return new;
end;
$$ language plpgsql;

-- Create triggers for updated_at
create trigger handle_updated_at
    before update on public.profiles
    for each row
    execute function public.handle_updated_at();

create trigger handle_updated_at
    before update on public.chats
    for each row
    execute function public.handle_updated_at();

create trigger handle_updated_at
    before update on public.messages
    for each row
    execute function public.handle_updated_at(); 